### ISSUE TITLE
Version number was not updated

### ISSUE THREAD

**Issue by Melcore79** [ericepalmer/ORExSPCsupport#3]
Hi Eric,
You updated the version number in the header, but didn't update the version number displayed by the program. You should back able to click the link below to go right to the line number.

Also, to access this folder I have to first navigate to your account. Shouldn't we put this folder is Sterephotoclinometry and not in your personal folder?

https://github.com/ericepalmer/ORExSPCsupport/blob/442dc07e56db39f71b9a7999d24874fe4d104ee3/phasei.f#L75

**Comment by ericepalmer** [comment]
Fixed
